---
- name: Ensure /opt/oulib/ojs/bin exists
  file:
    path: /opt/oulib/ojs/bin
    state: directory
    mode: 0755
    owner: root
    group: wheel
    recurse: yes

- name: scripts to /opt/oulib/ojs/bin
  copy:
    src: "{{ item }}"
    dest: /opt/oulib/ojs/bin/
    mode: 0755
    owner: root
    group: wheel
  with_items:
      - ojs_dump.sh
      - ojs_importdb.sh
      - ojs_restore.sh
      - ojs_snapshot.sh

- name: Ensure /opt/oulib/ojs/etc exists
  file:
    path: /opt/oulib/ojs/etc
    state: directory
    mode: 0755
    owner: root
    group: wheel
    recurse: yes

- name: Install ojs config
  template:
    src: ojs_conf.sh.j2
    dest: /opt/oulib/ojs/etc/ojs_conf.sh
    owner: root
    group: wheel
    mode: 0444

- name: Install cron scripts
  copy:
    src: "{{ item }}"
    dest: /etc/cron.daily/
    mode: 0755
    owner: root
    group: wheel
  with_items:
      - ojs_daily.cron
