---
- name: Set SELinux exceptions for apache
  command: "setsebool -P {{ item }} on"
  with_items:
  - httpd_can_network_connect_db
  - httpd_can_sendmail

- name: Set upload_max_filesize
  replace:
    dest: /etc/php.ini
    regexp: >
      ^upload_max_filesize = 2M$
    replace: "upload_max_filesize = 20M"

- name: Set post_max_size
  replace:
    dest: /etc/php.ini
    regexp: >
      ^post_max_size = 8M$
    replace: "post_max_size = 24M"

- name: Set PHP timezone
  replace:
    dest: /etc/php.ini
    regexp: >
      ^;date.timezone =$
    replace: "date.timezone = America/Chicago"

- name: Add config include to http.conf
  lineinfile:
    state: present
    dest: /etc/httpd/conf/httpd.conf
    line: "IncludeOptional \"{{ ojs_parent_dir }}/*/etc/*.conf\""

- name: Add OJS apache config
  template:
    src: srv_ojs.conf.j2
    dest: "{{ ojs_parent_dir }}/{{ ojs_sitename }}/etc/srv_ojs.conf"
    owner: root
    group: wheel
    mode: 0664

- name: Add OJS app config
  template:
    src: config.inc.php.j2
    dest: "{{ ojs_parent_dir }}/{{ ojs_sitename }}/ojs/config.inc.php"
    owner: root
    group: wheel
    mode: 0664
