---
- name: Set SELinux exceptions for apache
  command: "setsebool -P {{ item }} on"
  with_items:
  - httpd_can_network_connect_db
  - httpd_can_sendmail

- name: Set upload_max_filesize
  replace:
    dest: "/etc/opt/rh/{{ sclphp_version }}/php.ini" 
    regexp: >
      ^upload_max_filesize = 2M$
    replace: "upload_max_filesize = 64M"

- name: Set post_max_size
  replace:
    dest: "/etc/opt/rh/{{ sclphp_version }}/php.ini"
    regexp: >
      ^post_max_size = 8M$
    replace: "post_max_size = 68M"

- name: Set PHP timezone
  replace:
    dest: "/etc/opt/rh/{{ sclphp_version }}/php.ini"
    regexp: >
      ^;date.timezone =$
    replace: "date.timezone = America/Chicago"

- name: Set memory_limit
  replace:
    dest: "/etc/opt/rh/{{ sclphp_version }}/php.ini"
    regexp: >
      ^memory_limit = 128M$
    replace: "memory_limit = 256M"
