---
- name: ojs database
  mysql_db:
    name: "{{ ojs_mariadb_database }}"
    login_host: "{{ ojs_mariadb_host }}"
    login_port: "{{ ojs_mariadb_port }}"
    login_user: "{{ ojs_mariadb_login_username }}"
    login_password: "{{ ojs_mariadb_login_password }}"
    state: present
- name: ojs user for database
  mysql_user:
    name: "{{ ojs_mariadb_username }}"
    host: "{{ ojs_mariadb_userhost }}"
    password: "{{ ojs_mariadb_password }}"
    priv: "{{ ojs_mariadb_database }}.*:{{ ojs_mariadb_privileges }}"
    login_host: "{{ ojs_mariadb_host }}"
    login_port: "{{ ojs_mariadb_port }}"
    login_user: "{{ ojs_mariadb_login_username }}"
    login_password: "{{ ojs_mariadb_login_password }}"
    state: present
