---

- name: Calculate OJS install paths
  set_fact: 
    ojs_calculated_paths: 
       "{{ ojs_calculated_paths|default([]) + [ ojs_parent_dir + '/' + item.0.name +'/sites/' + item.1.path] }}"
  with_subelements:
    - "{{ ojs_sites }}" 
    - installs

- name: OJS site directories exist
  file:
    path: "{{ ojs_parent_dir }}/{{ item.0.name }}/sites/{{item.1.path }}"
    state: directory
    mode: 0775
    owner: root
    group: wheel
  with_subelements:
    - "{{ ojs_sites }}" 
    - installs

- name: OJS site subdirectories exist
  file:
    path: "{{ item.0}}/{{item.1}}"
    state: directory
    mode: 0775
    owner: apache
    group: apache
  with_nested:
    - "{{ojs_calculated_paths }}"
    - - db
      - etc
      - files
      - public
      - snapshots

- name: OJS site configs exist 
  template:
    src: config.inc.php.j2
    dest: "{{ ojs_parent_dir }}/{{ item.0.name }}/sites/{{item.1.path }}/etc/config.inc.php"
    mode: 0644
    owner: apache
    group: wheel
            
  with_subelements:
    - "{{ ojs_sites }}" 
    - installs

- name: Unarchive OJS
  unarchive:
    src: "/tmp/{{ ojs_tarball }}"
    dest: "{{item}}"
    creates:  "{{ item }}/ojs-{{ ojs_version }}/README.md"
    owner: apache
    group: apache
    copy: no
  with_items: "{{ojs_calculated_paths }}"

- name: Copy files from ojs/public to public
  command: >
    rsync --recursive --times --ignore-existing "{{ item }}/ojs-{{ ojs_version }}/public/" "{{ item }}/public"
  with_items: "{{ojs_calculated_paths }}"

- name: Remove public from ojs dist folder
  file:
    path: "{{ item }}/ojs-{{ ojs_version }}/public"
    state: absent
  with_items: "{{ojs_calculated_paths }}"

- name: Link to site public folder
  file:
    src: "{{ item }}/public"      
    path: "{{ item }}/ojs-{{ ojs_version }}/public"
    state: link
  with_items: "{{ojs_calculated_paths }}"

- name: Link ojs-$version directory to ojs
  file:
    src: "{{ item }}/ojs-{{ ojs_version }}"
    path: "{{ item }}/ojs"
    state: link
  with_items: "{{ojs_calculated_paths }}"


- name: Set default SELinux context for etc subdirectory
  command: >
    semanage fcontext -a -t httpd_config_t  "{{ item }}/etc(/.*)?"
  with_items: "{{ojs_calculated_paths }}"

- name: Set default SELinux context for ojs subdirectory
  command: >
    semanage fcontext -a -t httpd_sys_rw_content_t  "{{ item }}/ojs-{{ ojs_version }}(/.*)?"
  with_items: "{{ojs_calculated_paths }}"


- name: Set default SELinux context for files subdirectory
  command: >
    semanage fcontext -a -t httpd_sys_rw_content_t  "{{ item }}/files(/.*)?"
  with_items: "{{ojs_calculated_paths }}"


- name: Restore default SELinux context for OJS
  command: >
    restorecon -rv {{ item }}
  with_items: "{{ojs_calculated_paths }}"






