---
#- name: Check for current OJS code to site
#  stat:
#    path: "{{ item }}/ojs"
#  register: ojs_code
#
#- name: Set current version
#  set_fact:
#   current_version: "{{ ojs_code.stat.lnk_source | basename | regex_replace('ojs-', '') }}"
#  when: ojs_code.stat.lnk_source is defined
#
#- name: Clean current version
#  set_fact:
#   current_version: "{{ current_version.split('-') | join('.') }}"
#  when: ojs_code.stat.lnk_source is defined

- name: Download OJS tarball
  get_url:
    url: "{{ ojs_download_url }}{{ ojs_tarball }}"
    dest: "/tmp/{{ ojs_tarball }}"
    checksum: "md5:{{ ojs_md5sum }}"
  check_mode: no 

- name: Deploy OJS code to site
  unarchive:
    src: "/tmp/{{ ojs_tarball }}"
    dest: "{{item}}"
    creates:  "{{ item }}/ojs-{{ ojs_version }}/README.md"
    owner: nginx
    group: nginx
    copy: no
  register: deploy_ojs_code

# Run this block conditionally when new code is deployed
- name: Copy files from ojs/public to public
  command: >
    rsync --recursive --times --ignore-existing "{{ item }}/ojs-{{ ojs_version }}/public/" "{{ item }}/public"
  when: deploy_ojs_code.changed

- name: Remove public from ojs dist folder
  file:
    path: "{{ item }}/ojs-{{ ojs_version }}/public"
    state: absent

- name: Remove default config.inc.php from ojs-$version folder
  file:
    path: "{{ item }}/ojs-{{ ojs_version }}/config.inc.php"
    state: absent    
 
- name: Add link to public folder
  file:
    src: "{{ item }}/public"
    path: "{{ item }}/ojs-{{ ojs_version }}/public"
    state: link

- name: Remove default config.inc.php from ojs-$version folder
  file:
    path: "{{ item }}/ojs-{{ ojs_version }}/config.inc.php"
    state: absent

- name: Add link to config.inc.php to ojs-$version dir
  file:
    src: "{{ item }}/etc/config.inc.php"
    path: "{{ item }}/ojs-{{ ojs_version }}/config.inc.php"
    state: link

- name: Link ojs-$version directory to ojs
  file:
    src: "{{ item }}/ojs-{{ ojs_version }}"
    path: "{{ item }}/ojs"
    state: link

# TODO Is this conditional needed?
#
#  when: ojs_code.stat.lnk_source is defined and current_version is version( ojs_version, '<')
#
# TODO should we copy themes?
#
#- name: Copy Themes from previous install
#  command: >
#  rsync --ignore-existing --recursive "{{ ojs_code.stat.lnk_source }}/plugins/themes/" "{{ item }}/ojs-{{ ojs_version }}/plugins/themes/"

- name: Set SELinux context for etc subdirectory
  command: >
    semanage fcontext -a -t httpd_config_t  "{{ item }}/etc(/.*)?"

- name: Set SELinux context for ojs subdirectory
  command: >
    semanage fcontext -a -t httpd_sys_rw_content_t  "{{ item }}/ojs-{{ ojs_version }}(/.*)?"

- name: Set SELinux context for public subdirectory
  command: >
    semanage fcontext -a -t httpd_sys_rw_content_t  "{{ item }}/public(/.*)?"

- name: Set  SELinux context for files subdirectory
  command: >
    semanage fcontext -a -t httpd_sys_rw_content_t  "{{ item }}/files(/.*)?"

- name: Apply SELinux context for OJS installs
  command: >
    restorecon -rv {{ item }}



