---
- name: OJS site directory exists
  file:
    path: "{{ ojs_parent_dir }}/{{ ojs_sitename }}"
    state: directory
    mode: 0775
    owner: root
    group: wheel

- name: OJS subdirectories exists
  file:
    path: "{{ ojs_parent_dir }}/{{ ojs_sitename }}/{{ item }}"
    state: directory
    mode: 0775
    owner: apache
    group: apache
  with_items:
    - public
    - files
    - etc

- name: Unarchive OJS
  unarchive:
    src: "/tmp/{{ ojs_tarball }}"
    dest: "{{ ojs_parent_dir }}/{{ ojs_sitename }}"
    owner: apache
    group: apache
    copy: no

- name: Copy files from ojs/public to public
  copy:
    remote_src: True
    src: "{{ ojs_parent_dir }}/{{ ojs_sitename }}/ojs-{{ ojs_version }}/public/"
    dest: "{{ ojs_parent_dir }}/{{ ojs_sitename }}/public"

- name: Remove ojs/public
  file:
    path: "{{ ojs_parent_dir }}/{{ ojs_sitename }}/ojs-{{ ojs_version }}/public"
    state: absent

- name: Link ojs/public to public
  file:
    src: "{{ ojs_parent_dir }}/{{ ojs_sitename }}/public"
    path: "{{ ojs_parent_dir }}/{{ ojs_sitename }}/ojs-{{ ojs_version }}/public"
    state: link

- name: Link ojs-$version directory to ojs
  file:
    src: "{{ ojs_parent_dir }}/{{ ojs_sitename }}/ojs-{{ ojs_version }}"
    path: "{{ ojs_parent_dir }}/{{ ojs_sitename }}/ojs"
    state: link
