---
- name: OJS site directory exists
  file:
    path: "{{ ojs_parent_dir }}/{{ ojs_site_name }}"
    state: directory
    mode: 0775
    owner: root
    group: wheel

- name: OJS subdirectories exists
  file:
    path: "{{ ojs_parent_dir }}/{{ ojs_site_name }}/{{ item }}"
    state: directory
    mode: 0775
    owner: apache
    group: apache
  with_items:
    - db
    - etc
    - files
    - public
    - snapshots

- name: Unarchive OJS
  unarchive:
    src: "/tmp/{{ ojs_tarball }}"
    dest: "{{ ojs_parent_dir }}/{{ ojs_site_name }}"
    owner: apache
    group: apache
    copy: no

- name: Copy files from ojs/public to public
  command: >
    rsync --recursive --times --ignore-existing "{{ ojs_parent_dir }}/{{ ojs_site_name }}/ojs-{{ ojs_version }}/public/" "{{ ojs_parent_dir }}/{{ ojs_site_name }}/public"
  become: true

- name: Remove ojs/public
  file:
    path: "{{ ojs_parent_dir }}/{{ ojs_site_name }}/ojs-{{ ojs_version }}/public"
    state: absent

- name: Link ojs/public to public
  file:
    src: "{{ ojs_parent_dir }}/{{ ojs_site_name }}/public"
    path: "{{ ojs_parent_dir }}/{{ ojs_site_name }}/ojs-{{ ojs_version }}/public"
    state: link

- name: Link ojs-$version directory to ojs
  file:
    src: "{{ ojs_parent_dir }}/{{ ojs_site_name }}/ojs-{{ ojs_version }}"
    path: "{{ ojs_parent_dir }}/{{ ojs_site_name }}/ojs"
    state: link
