---
# Create persistent code and config for journals
- name: Calculate OJS install paths
  set_fact: 
    ojs_calculated_paths: 
       "{{ ojs_calculated_paths|default([]) + [ ojs_parent_dir + '/' + item.0.name +'/sites/' + item.1.path] }}"
  with_subelements:
    - "{{ ojs_sites }}" 
    - installs

- name: OJS site directories exist
  file:
    path: "{{ ojs_parent_dir }}/{{ item.0.name }}/sites/{{item.1.path }}"
    state: directory
    mode: 0775
    owner: root
    group: wheel
  with_subelements:
    - "{{ ojs_sites }}" 
    - installs

- name: OJS site subdirectories exist
  file:
    path: "{{ item.0}}/{{item.1}}"
    state: directory
    mode: 0775
    owner: nginx
    group: nginx
  with_nested:
    - "{{ojs_calculated_paths }}"
    - - db
      - etc
      - files
      - public
      - snapshots

- name: OJS site configs exist 
  template:
    src: config.inc.php.j2
    dest: "{{ ojs_parent_dir }}/{{ item.0.name }}/sites/{{item.1.path }}/etc/config.inc.php"
    mode: 0644
    force: no        
    owner: nginx
    group: nginx
  with_subelements:
    - "{{ ojs_sites }}" 
    - installs

# Deploy source code and connect to persistent code and config created above
- include: deploy_src.yml    
  with_items: "{{ojs_calculated_paths }}"  
