---
# tasks file for OJS

- include: yum.yml
  become: true
  tags: ojs_yum

- include: pip.yml
  become: true
  tags: ojs_pip

- include: assets.yml
  become: true
  tags: ojs_assets

- include: get.yml
  become: true
  tags: ojs_get

- include: deploy.yml
  become: true
  tags: ojs_deploy

- include: configure.yml
  become: true
  tags: ojs_configure

- include: database.yml
  become: true
  tags: ojs_database

- include: install.yml
  become: true
  tags: ojs_install

- include: services.yml
  become: true
  tags: ojs_services
