---
# tasks file for OJS

- include: assets.yml
  become: true
  tags: ojs_assets

- include: get.yml
  become: true
  tags: ojs_get

- include: deploy.yml
  become: true
  tags: ojs_deploy

#- include: configure.yml
  #become: true
  #tags: ojs_configure

#- include: install.yml
  #become: true
  #tags: ojs_install

- include: nginx.yml
  become: true
  tags: ojs_nginx
