---
# tasks file for OJS

- include: yum.yml
  sudo: yes

- include: pip.yml
  sudo: yes

- include: get.yml
  sudo: yes

- include: deploy.yml
  sudo: yes

- include: configure.yml
  sudo: yes

- include: database.yml
  sudo: yes

- include: install.yml
  sudo: yes

- include: services.yml
  sudo: yes
