---

- name: Download, deploy, and install additional OJS plugins
  block:
    - name: "Download standard OJS plugins"
      get_url:
        url: "{{ plugin.url }}/{{ plugin.tarball }}"
        dest: "/tmp/{{ plugin.tarball }}"
        checksum: "md5:{{ plugin.md5sum }}"
      check_mode: no
      loop: "{{ ojs_plugins }}"
      loop_control:
        loop_var: plugin

    - name: "Deploy standard OJS plugins"
      unarchive:
        src: "/tmp/{{ plugin.tarball }}"
        dest: "{{item}}/ojs-{{ ojs_version }}/plugins/{{ plugin.category }}"
        creates: "{{item}}/ojs-{{ ojs_version }}/plugins/{{ plugin.category }}/{{ plugin.name }}/version.xml"        
        owner: nginx
        group: nginx
        mode: 0775
        copy: no
      register: plugins_deployed
      loop: "{{ ojs_plugins }}"
      loop_control:
        loop_var: plugin

    - name: "Install standard OJS plugins"
      command: >
        {{ sclphp_location }} installPluginVersion.php
        "{{ item }}/ojs-{{ ojs_version }}/plugins/{{ plugin.category }}/{{ plugin.name }}/version.xml"
      args:
        chdir: "{{ item }}/ojs-{{ ojs_version }}/lib/pkp/tools/"
      loop: "{{ ojs_plugins }}"
      loop_control:
        loop_var: plugin
      when: plugins_deployed.changed
  tags: ojs_plugins
